export default {
  types: {
    core: { title: '🔥 Core' },
    feat: { title: '🚀 Features' },
    fix: { title: '🐛 Fixes' },
    perf: { title: '🏎 Performance' },
    refactor: { title: '🔨 Refactor' },
    revert: { title: '⏪ Reverts' },
    i18n: { title: '🌐 I18n' },
    a11y: { title: '♿️ Accessibility' },
    report: { title: '📊 Report' },
    cli: { title: '🖥 CLI' },
    audits: { title: '🔍 Audits' },
    misc: { title: '🎫 Misc' },
    wip: { title: '🚧 WIP' },
    docs: { title: '📖 Documentation' },
    build: { title: '📦 Build' },
    types: { title: '🏷 Types' },
    chore: { title: '🏡 Chores' },
    examples: { title: '📚 Examples' },
    test: { title: '🧪 Tests' },
    dx: { title: '🛠 DX' },
    style: { title: '💄 Style' },
    ci: { title: '🤖 CI' },
    workflow: { title: '🔧 Workflow' },
    release: { title: '🚢 Release' },
    deps: { title: '📦 Dependencies' },
    improve: { title: '👌 Improvements' },
    security: { title: '🔒 Security' },
    deprecated: { title: '🗑 Deprecated' },
  },
}
