export const VIRTUAL_VUETIFY_CONFIGURATION = 'virtual:vuetify-configuration'
export const RESOLVED_VIRTUAL_VUETIFY_CONFIGURATION = `\0${VIRTUAL_VUETIFY_CONFIGURATION}`
export const VIRTUAL_VUETIFY_DATE_CONFIGURATION = 'virtual:vuetify-date-configuration'
export const RESOLVED_VIRTUAL_VUETIFY_DATE_CONFIGURATION = `\0${VIRTUAL_VUETIFY_DATE_CONFIGURATION}`
export const VIRTUAL_VUETIFY_ICONS_CONFIGURATION = 'virtual:vuetify-icons-configuration'
export const RESOLVED_VIRTUAL_VUETIFY_ICONS_CONFIGURATION = `\0${VIRTUAL_VUETIFY_ICONS_CONFIGURATION}`
export const VIRTUAL_VUETIFY_SSR_CLIENT_HINTS_CONFIGURATION = 'virtual:vuetify-ssr-client-hints-configuration'
export const RESOLVED_VIRTUAL_VUETIFY_SSR_CLIENT_HINTS_CONFIGURATION = `\0${VIRTUAL_VUETIFY_SSR_CLIENT_HINTS_CONFIGURATION}`

export const RESOLVED_VIRTUAL_MODULES = [
  RESOLVED_VIRTUAL_VUETIFY_DATE_CONFIGURATION,
  RESOLVED_VIRTUAL_VUETIFY_ICONS_CONFIGURATION,
  RESOLVED_VIRTUAL_VUETIFY_CONFIGURATION,
  RESOLVED_VIRTUAL_VUETIFY_SSR_CLIENT_HINTS_CONFIGURATION,
]
